### PR TITLE
Fix mobile nav menu formatting

### LINKED ISSUE #46: Mobile nav menu formatting
In Mobile the menu is all there and aligned but the first option is highlighted as if you are hovering on it and cannot be moved and makes the option hard to read because of the color. In mobile we don't need the hover option for the menu could we remove it? Also can we make the search button the same size and coloring/format as the others menu options?

[EDIT] That search button also is not fully clickable. Right now you have to hit the search icon to make it work. Need to make it so the entire search button bar is clickable like the rest of the menu.

Capture2

### PR DESCRIPTION
**Pull request by foxyblocks**
fixes #46

This PR does a few things.

### 1. Fix mobile navigation

Updated the mobile navigation so it no longer looks broken on mobile. I also opted for a `<Drawer />` component instead of a `<Menu />` so that it doesn't cause the UI to "jump" on mobile and so we don't get weird "focus" state of the active menu item.

CleanShot 2021-09-05 at 14 13 16@2x

CleanShot 2021-09-05 at 14 12 51

### 2. Rename the fonts in the chakra theme
I renamed these fonts to have more discernible names than "one", "two" etc... and added them to the chakra theme so that they can be referenced from component props.

### 3. Added some color variables to the chakra theme.

Moved some of the color variables to the chakra theme so that we can use them in component props without css vars. Also gave them some more friendly names that relate to visual appearance of the color.

### 4. Setup default button styles
Added a `solid` button style to chakra theme so buttons will default to the solid red style.

### CODE REVIEW

File: theme/fonts.ts [hunk 1]
```diff
@@ -1,6 +1,5 @@
 export default {
-    one: "Spartan",
-    two: "Spartan",
-    three: "Mulish",
-    four: "Source Code Pro"
-}
\ No newline at end of file
+  spartan: 'Spartan',
+  mulish: 'Mulish',
+  mono: 'Source Code Pro',
```
Comment (zberwaldt) [inline theme/fonts.ts:4]: Thank you, can't believe I double-declared the Spartan font.

File: theme/styles.ts [hunk 2]
```diff
@@ -1,1043 +1,1030 @@
-import { background, flexbox } from "@chakra-ui/react";
+/*
+ TODO: TURN MOST OF THESE STYLES INTO NON-GLOBAL STYLES BY USING COMPONENTS OR STYLE MIXINS
 
+ PLEASE TRY NOT TO ADD ANYTHING TO THIS FILE.
+*/
```
Comment (zberwaldt) [inline theme/styles.ts:5]: For the remainder of the season, I will be going maintenance mode

- Baking this file into chakra styles is one of the main items I will address.

**Review by zberwaldt — APPROVED** [review]
Much appreciated.
